# Generated by Django 2.1.7 on 2019-03-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_newfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='newfield',
        ),
    ]
